create table companies(
    id bigint primary key GENERATED BY DEFAULT AS IDENTITY,
    name text not null UNIQUE
);

create table employees(
    id bigint primary key GENERATED BY DEFAULT AS IDENTITY,
    name text not null,
    surname text not null,
    email text not null UNIQUE,
    address text not null,
    salary decimal not null,
    company_id bigint references companies(id) not null,
    constraint salary_nonnegative check (salary > 0)
);